/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FormCategory = IDL.Variant({
  'bpl' : IDL.Null,
  'revenue' : IDL.Null,
  'construction' : IDL.Null,
  'rationCard' : IDL.Null,
  'birthDeath' : IDL.Null,
  'panchayat' : IDL.Null,
  'income' : IDL.Null,
  'marriage' : IDL.Null,
  'nrega' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FieldType = IDL.Variant({
  'date' : IDL.Null,
  'text' : IDL.Null,
  'document' : ExternalBlob,
  'number' : IDL.Null,
  'checkbox' : IDL.Null,
  'dropdown' : IDL.Vec(IDL.Text),
});
export const FormField = IDL.Record({
  'required' : IDL.Bool,
  'fieldName' : IDL.Text,
  'fieldType' : FieldType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'documentsRequired' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'applicationLink' : IDL.Text,
});
export const Form = IDL.Record({
  'id' : IDL.Nat,
  'feeAmount' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'instructions' : IDL.Text,
  'fields' : IDL.Vec(FormField),
  'category' : FormCategory,
});
export const Time = IDL.Int;
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'date' : Time,
  'type' : IDL.Text,
  'caption' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'published' : IDL.Bool,
  'author' : IDL.Principal,
  'language' : IDL.Text,
});
export const ServiceLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'status' : SubmissionStatus,
  'user' : IDL.Principal,
  'fieldValues' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat8))),
  'timestamp' : Time,
  'formId' : IDL.Nat,
});
export const SubscriptionType = IDL.Variant({
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'subscriptionExpiry' : Time,
  'name' : IDL.Text,
  'subscriptionType' : SubscriptionType,
  'district' : IDL.Text,
  'taluka' : IDL.Text,
  'village' : IDL.Text,
  'mobile' : IDL.Text,
});
export const SiteInfo = IDL.Record({
  'socialLinks' : IDL.Vec(IDL.Text),
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addForm' : IDL.Func(
      [IDL.Text, FormCategory, IDL.Text, IDL.Nat, IDL.Vec(FormField), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addScheme' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addServiceLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteForm' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deleteScheme' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceLink' : IDL.Func([IDL.Nat], [], []),
  'editForm' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        FormCategory,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(FormField),
        IDL.Text,
      ],
      [],
      [],
    ),
  'editPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'editScheme' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'editServiceLink' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllActiveSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getAllForms' : IDL.Func([], [IDL.Vec(Form)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getAllServiceLinks' : IDL.Func([], [IDL.Vec(ServiceLink)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getForm' : IDL.Func([IDL.Nat], [IDL.Opt(Form)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
  'getPublishedPostsByLanguage' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Post)],
      ['query'],
    ),
  'getSiteInfo' : IDL.Func([], [IDL.Opt(SiteInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFormSubmission' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat8)))],
      [IDL.Nat],
      [],
    ),
  'updateSiteInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateSubmissionStatus' : IDL.Func([IDL.Nat, SubmissionStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FormCategory = IDL.Variant({
    'bpl' : IDL.Null,
    'revenue' : IDL.Null,
    'construction' : IDL.Null,
    'rationCard' : IDL.Null,
    'birthDeath' : IDL.Null,
    'panchayat' : IDL.Null,
    'income' : IDL.Null,
    'marriage' : IDL.Null,
    'nrega' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FieldType = IDL.Variant({
    'date' : IDL.Null,
    'text' : IDL.Null,
    'document' : ExternalBlob,
    'number' : IDL.Null,
    'checkbox' : IDL.Null,
    'dropdown' : IDL.Vec(IDL.Text),
  });
  const FormField = IDL.Record({
    'required' : IDL.Bool,
    'fieldName' : IDL.Text,
    'fieldType' : FieldType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'documentsRequired' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'applicationLink' : IDL.Text,
  });
  const Form = IDL.Record({
    'id' : IDL.Nat,
    'feeAmount' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'instructions' : IDL.Text,
    'fields' : IDL.Vec(FormField),
    'category' : FormCategory,
  });
  const Time = IDL.Int;
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'date' : Time,
    'type' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'published' : IDL.Bool,
    'author' : IDL.Principal,
    'language' : IDL.Text,
  });
  const ServiceLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'status' : SubmissionStatus,
    'user' : IDL.Principal,
    'fieldValues' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat8))),
    'timestamp' : Time,
    'formId' : IDL.Nat,
  });
  const SubscriptionType = IDL.Variant({
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'subscriptionExpiry' : Time,
    'name' : IDL.Text,
    'subscriptionType' : SubscriptionType,
    'district' : IDL.Text,
    'taluka' : IDL.Text,
    'village' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const SiteInfo = IDL.Record({
    'socialLinks' : IDL.Vec(IDL.Text),
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addForm' : IDL.Func(
        [
          IDL.Text,
          FormCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(FormField),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addScheme' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addServiceLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteForm' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deleteScheme' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceLink' : IDL.Func([IDL.Nat], [], []),
    'editForm' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          FormCategory,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(FormField),
          IDL.Text,
        ],
        [],
        [],
      ),
    'editPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'editScheme' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'editServiceLink' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllActiveSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getAllForms' : IDL.Func([], [IDL.Vec(Form)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getAllServiceLinks' : IDL.Func([], [IDL.Vec(ServiceLink)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getForm' : IDL.Func([IDL.Nat], [IDL.Opt(Form)], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
    'getPublishedPostsByLanguage' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Post)],
        ['query'],
      ),
    'getSiteInfo' : IDL.Func([], [IDL.Opt(SiteInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFormSubmission' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat8)))],
        [IDL.Nat],
        [],
      ),
    'updateSiteInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateSubmissionStatus' : IDL.Func([IDL.Nat, SubmissionStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };