/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FieldType = { 'date' : null } |
  { 'text' : null } |
  { 'document' : ExternalBlob } |
  { 'number' : null } |
  { 'checkbox' : null } |
  { 'dropdown' : Array<string> };
export interface Form {
  'id' : bigint,
  'feeAmount' : bigint,
  'title' : string,
  'description' : string,
  'instructions' : string,
  'fields' : Array<FormField>,
  'category' : FormCategory,
}
export type FormCategory = { 'bpl' : null } |
  { 'revenue' : null } |
  { 'construction' : null } |
  { 'rationCard' : null } |
  { 'birthDeath' : null } |
  { 'panchayat' : null } |
  { 'income' : null } |
  { 'marriage' : null } |
  { 'nrega' : null };
export interface FormField {
  'required' : boolean,
  'fieldName' : string,
  'fieldType' : FieldType,
}
export interface FormSubmission {
  'id' : bigint,
  'status' : SubmissionStatus,
  'user' : Principal,
  'fieldValues' : Array<[string, Uint8Array]>,
  'timestamp' : Time,
  'formId' : bigint,
}
export interface GalleryItem {
  'id' : bigint,
  'blob' : ExternalBlob,
  'date' : Time,
  'type' : string,
  'caption' : string,
}
export interface Post {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : Time,
  'published' : boolean,
  'author' : Principal,
  'language' : string,
}
export interface Scheme {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'documentsRequired' : Array<string>,
  'category' : string,
  'applicationLink' : string,
}
export interface ServiceLink {
  'id' : bigint,
  'url' : string,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface SiteInfo {
  'socialLinks' : Array<string>,
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type SubmissionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type SubscriptionType = { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export type Time = bigint;
export interface UserProfile {
  'subscriptionExpiry' : Time,
  'name' : string,
  'subscriptionType' : SubscriptionType,
  'district' : string,
  'taluka' : string,
  'village' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addForm' : ActorMethod<
    [string, FormCategory, string, bigint, Array<FormField>, string],
    bigint
  >,
  'addGalleryItem' : ActorMethod<[string, ExternalBlob, string], bigint>,
  'addScheme' : ActorMethod<
    [string, string, string, Array<string>, string, boolean],
    bigint
  >,
  'addServiceLink' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string, string, boolean], bigint>,
  'deleteForm' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteScheme' : ActorMethod<[bigint], undefined>,
  'deleteServiceLink' : ActorMethod<[bigint], undefined>,
  'editForm' : ActorMethod<
    [bigint, string, FormCategory, string, bigint, Array<FormField>, string],
    undefined
  >,
  'editPost' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'editScheme' : ActorMethod<
    [bigint, string, string, string, Array<string>, string, boolean],
    undefined
  >,
  'editServiceLink' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'getAllActiveSchemes' : ActorMethod<[], Array<Scheme>>,
  'getAllForms' : ActorMethod<[], Array<Form>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllPublishedPosts' : ActorMethod<[], Array<Post>>,
  'getAllSchemes' : ActorMethod<[], Array<Scheme>>,
  'getAllServiceLinks' : ActorMethod<[], Array<ServiceLink>>,
  'getAllSubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getForm' : ActorMethod<[bigint], [] | [Form]>,
  'getMySubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getPublishedPostsByLanguage' : ActorMethod<[string], Array<Post>>,
  'getSiteInfo' : ActorMethod<[], [] | [SiteInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFormSubmission' : ActorMethod<
    [bigint, Array<[string, Uint8Array]>],
    bigint
  >,
  'updateSiteInfo' : ActorMethod<
    [string, string, string, string, Array<string>],
    undefined
  >,
  'updateSubmissionStatus' : ActorMethod<[bigint, SubmissionStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];