/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface FormField {
    required: boolean;
    fieldName: string;
    fieldType: FieldType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FormSubmission {
    id: bigint;
    status: SubmissionStatus;
    user: Principal;
    fieldValues: Array<[string, Uint8Array]>;
    timestamp: Time;
    formId: bigint;
}
export interface Form {
    id: bigint;
    feeAmount: bigint;
    title: string;
    description: string;
    instructions: string;
    fields: Array<FormField>;
    category: FormCategory;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Scheme {
    id: bigint;
    title: string;
    active: boolean;
    description: string;
    documentsRequired: Array<string>;
    category: string;
    applicationLink: string;
}
export interface ServiceLink {
    id: bigint;
    url: string;
    name: string;
    description: string;
    category: string;
}
export interface Post {
    id: bigint;
    title: string;
    content: string;
    date: Time;
    published: boolean;
    author: Principal;
    language: string;
}
export type FieldType = {
    __kind__: "date";
    date: null;
} | {
    __kind__: "text";
    text: null;
} | {
    __kind__: "document";
    document: ExternalBlob;
} | {
    __kind__: "number";
    number: null;
} | {
    __kind__: "checkbox";
    checkbox: null;
} | {
    __kind__: "dropdown";
    dropdown: Array<string>;
};
export interface GalleryItem {
    id: bigint;
    blob: ExternalBlob;
    date: Time;
    type: string;
    caption: string;
}
export interface SiteInfo {
    socialLinks: Array<string>;
    whatsapp: string;
    email: string;
    address: string;
    phone: string;
}
export interface UserProfile {
    subscriptionExpiry: Time;
    name: string;
    subscriptionType: SubscriptionType;
    district: string;
    taluka: string;
    village: string;
    mobile: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FormCategory {
    bpl = "bpl",
    revenue = "revenue",
    construction = "construction",
    rationCard = "rationCard",
    birthDeath = "birthDeath",
    panchayat = "panchayat",
    income = "income",
    marriage = "marriage",
    nrega = "nrega"
}
export enum SubmissionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum SubscriptionType {
    annual = "annual",
    quarterly = "quarterly",
    monthly = "monthly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addForm(title: string, category: FormCategory, description: string, feeAmount: bigint, fields: Array<FormField>, instructions: string): Promise<bigint>;
    addGalleryItem(type: string, blob: ExternalBlob, caption: string): Promise<bigint>;
    addScheme(title: string, description: string, category: string, documentsRequired: Array<string>, applicationLink: string, active: boolean): Promise<bigint>;
    addServiceLink(name: string, url: string, category: string, description: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(title: string, content: string, language: string, published: boolean): Promise<bigint>;
    deleteForm(formId: bigint): Promise<void>;
    deleteGalleryItem(itemId: bigint): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    deleteScheme(schemeId: bigint): Promise<void>;
    deleteServiceLink(linkId: bigint): Promise<void>;
    editForm(formId: bigint, title: string, category: FormCategory, description: string, feeAmount: bigint, fields: Array<FormField>, instructions: string): Promise<void>;
    editPost(postId: bigint, title: string, content: string, language: string, published: boolean): Promise<void>;
    editScheme(schemeId: bigint, title: string, description: string, category: string, documentsRequired: Array<string>, applicationLink: string, active: boolean): Promise<void>;
    editServiceLink(linkId: bigint, name: string, url: string, category: string, description: string): Promise<void>;
    getAllActiveSchemes(): Promise<Array<Scheme>>;
    getAllForms(): Promise<Array<Form>>;
    getAllGalleryItems(): Promise<Array<GalleryItem>>;
    getAllPosts(): Promise<Array<Post>>;
    getAllPublishedPosts(): Promise<Array<Post>>;
    getAllSchemes(): Promise<Array<Scheme>>;
    getAllServiceLinks(): Promise<Array<ServiceLink>>;
    getAllSubmissions(): Promise<Array<FormSubmission>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getForm(formId: bigint): Promise<Form | null>;
    getMySubmissions(): Promise<Array<FormSubmission>>;
    getPublishedPostsByLanguage(language: string): Promise<Array<Post>>;
    getSiteInfo(): Promise<SiteInfo | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitFormSubmission(formId: bigint, fieldValues: Array<[string, Uint8Array]>): Promise<bigint>;
    updateSiteInfo(phone: string, whatsapp: string, email: string, address: string, socialLinks: Array<string>): Promise<void>;
    updateSubmissionStatus(submissionId: bigint, status: SubmissionStatus): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, FieldType as _FieldType, Form as _Form, FormCategory as _FormCategory, FormField as _FormField, FormSubmission as _FormSubmission, GalleryItem as _GalleryItem, SiteInfo as _SiteInfo, SubmissionStatus as _SubmissionStatus, SubscriptionType as _SubscriptionType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addForm(arg0: string, arg1: FormCategory, arg2: string, arg3: bigint, arg4: Array<FormField>, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addForm(arg0, to_candid_FormCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addForm(arg0, to_candid_FormCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: ExternalBlob, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, await to_candid_ExternalBlob_n15(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addScheme(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addScheme(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScheme(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addServiceLink(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceLink(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceLink(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteForm(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteForm(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteScheme(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheme(arg0);
            return result;
        }
    }
    async deleteServiceLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceLink(arg0);
            return result;
        }
    }
    async editForm(arg0: bigint, arg1: string, arg2: FormCategory, arg3: string, arg4: bigint, arg5: Array<FormField>, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editForm(arg0, arg1, to_candid_FormCategory_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editForm(arg0, arg1, to_candid_FormCategory_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async editPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async editScheme(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editScheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editScheme(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async editServiceLink(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editServiceLink(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editServiceLink(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAllActiveSchemes(): Promise<Array<Scheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveSchemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveSchemes();
            return result;
        }
    }
    async getAllForms(): Promise<Array<Form>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllForms();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllForms();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItems();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItems();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return result;
        }
    }
    async getAllPublishedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublishedPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublishedPosts();
            return result;
        }
    }
    async getAllSchemes(): Promise<Array<Scheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSchemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSchemes();
            return result;
        }
    }
    async getAllServiceLinks(): Promise<Array<ServiceLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceLinks();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForm(arg0: bigint): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForm(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForm(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmissions(): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPostsByLanguage(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPostsByLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPostsByLanguage(arg0);
            return result;
        }
    }
    async getSiteInfo(): Promise<SiteInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteInfo();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteInfo();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFormSubmission(arg0: bigint, arg1: Array<[string, Uint8Array]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFormSubmission(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFormSubmission(arg0, arg1);
            return result;
        }
    }
    async updateSiteInfo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteInfo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteInfo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSubmissionStatus(arg0: bigint, arg1: SubmissionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SubmissionStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatus(arg0, to_candid_SubmissionStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FieldType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldType): Promise<FieldType> {
    return await from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_FormCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormCategory): FormCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_FormField_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormField): Promise<FormField> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_FormSubmission_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormSubmission): FormSubmission {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Form_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Form): Promise<Form> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_GalleryItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionType): SubscriptionType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Form]): Promise<Form | null> {
    return value.length === 0 ? null : await from_candid_Form_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SiteInfo]): SiteInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    feeAmount: bigint;
    title: string;
    description: string;
    instructions: string;
    fields: Array<_FormField>;
    category: _FormCategory;
}): Promise<{
    id: bigint;
    feeAmount: bigint;
    title: string;
    description: string;
    instructions: string;
    fields: Array<FormField>;
    category: FormCategory;
}> {
    return {
        id: value.id,
        feeAmount: value.feeAmount,
        title: value.title,
        description: value.description,
        instructions: value.instructions,
        fields: await from_candid_vec_n21(_uploadFile, _downloadFile, value.fields),
        category: from_candid_FormCategory_n27(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    required: boolean;
    fieldName: string;
    fieldType: _FieldType;
}): Promise<{
    required: boolean;
    fieldName: string;
    fieldType: FieldType;
}> {
    return {
        required: value.required,
        fieldName: value.fieldName,
        fieldType: await from_candid_FieldType_n24(_uploadFile, _downloadFile, value.fieldType)
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    date: _Time;
    type: string;
    caption: string;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    date: Time;
    type: string;
    caption: string;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.blob),
        date: value.date,
        type: value.type,
        caption: value.caption
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SubmissionStatus;
    user: Principal;
    fieldValues: Array<[string, Uint8Array]>;
    timestamp: _Time;
    formId: bigint;
}): {
    id: bigint;
    status: SubmissionStatus;
    user: Principal;
    fieldValues: Array<[string, Uint8Array]>;
    timestamp: Time;
    formId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_SubmissionStatus_n35(_uploadFile, _downloadFile, value.status),
        user: value.user,
        fieldValues: value.fieldValues,
        timestamp: value.timestamp,
        formId: value.formId
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscriptionExpiry: _Time;
    name: string;
    subscriptionType: _SubscriptionType;
    district: string;
    taluka: string;
    village: string;
    mobile: string;
}): {
    subscriptionExpiry: Time;
    name: string;
    subscriptionType: SubscriptionType;
    district: string;
    taluka: string;
    village: string;
    mobile: string;
} {
    return {
        subscriptionExpiry: value.subscriptionExpiry,
        name: value.name,
        subscriptionType: from_candid_SubscriptionType_n40(_uploadFile, _downloadFile, value.subscriptionType),
        district: value.district,
        taluka: value.taluka,
        village: value.village,
        mobile: value.mobile
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: null;
} | {
    text: null;
} | {
    document: _ExternalBlob;
} | {
    number: null;
} | {
    checkbox: null;
} | {
    dropdown: Array<string>;
}): Promise<{
    __kind__: "date";
    date: null;
} | {
    __kind__: "text";
    text: null;
} | {
    __kind__: "document";
    document: ExternalBlob;
} | {
    __kind__: "number";
    number: null;
} | {
    __kind__: "checkbox";
    checkbox: null;
} | {
    __kind__: "dropdown";
    dropdown: Array<string>;
}> {
    return "date" in value ? {
        __kind__: "date",
        date: value.date
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : "document" in value ? {
        __kind__: "document",
        document: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.document)
    } : "number" in value ? {
        __kind__: "number",
        number: value.number
    } : "checkbox" in value ? {
        __kind__: "checkbox",
        checkbox: value.checkbox
    } : "dropdown" in value ? {
        __kind__: "dropdown",
        dropdown: value.dropdown
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bpl: null;
} | {
    revenue: null;
} | {
    construction: null;
} | {
    rationCard: null;
} | {
    birthDeath: null;
} | {
    panchayat: null;
} | {
    income: null;
} | {
    marriage: null;
} | {
    nrega: null;
}): FormCategory {
    return "bpl" in value ? FormCategory.bpl : "revenue" in value ? FormCategory.revenue : "construction" in value ? FormCategory.construction : "rationCard" in value ? FormCategory.rationCard : "birthDeath" in value ? FormCategory.birthDeath : "panchayat" in value ? FormCategory.panchayat : "income" in value ? FormCategory.income : "marriage" in value ? FormCategory.marriage : "nrega" in value ? FormCategory.nrega : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): SubmissionStatus {
    return "pending" in value ? SubmissionStatus.pending : "approved" in value ? SubmissionStatus.approved : "rejected" in value ? SubmissionStatus.rejected : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    quarterly: null;
} | {
    monthly: null;
}): SubscriptionType {
    return "annual" in value ? SubscriptionType.annual : "quarterly" in value ? SubscriptionType.quarterly : "monthly" in value ? SubscriptionType.monthly : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Form>): Promise<Array<Form>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Form_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormField>): Promise<Array<FormField>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FormField_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormSubmission>): Array<FormSubmission> {
    return value.map((x)=>from_candid_FormSubmission_n33(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FieldType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldType): Promise<_FieldType> {
    return await to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_FormCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormCategory): _FormCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_FormField_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormField): Promise<_FormField> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionType): _SubscriptionType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    required: boolean;
    fieldName: string;
    fieldType: FieldType;
}): Promise<{
    required: boolean;
    fieldName: string;
    fieldType: _FieldType;
}> {
    return {
        required: value.required,
        fieldName: value.fieldName,
        fieldType: await to_candid_FieldType_n13(_uploadFile, _downloadFile, value.fieldType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscriptionExpiry: Time;
    name: string;
    subscriptionType: SubscriptionType;
    district: string;
    taluka: string;
    village: string;
    mobile: string;
}): {
    subscriptionExpiry: _Time;
    name: string;
    subscriptionType: _SubscriptionType;
    district: string;
    taluka: string;
    village: string;
    mobile: string;
} {
    return {
        subscriptionExpiry: value.subscriptionExpiry,
        name: value.name,
        subscriptionType: to_candid_SubscriptionType_n48(_uploadFile, _downloadFile, value.subscriptionType),
        district: value.district,
        taluka: value.taluka,
        village: value.village,
        mobile: value.mobile
    };
}
async function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "date";
    date: null;
} | {
    __kind__: "text";
    text: null;
} | {
    __kind__: "document";
    document: ExternalBlob;
} | {
    __kind__: "number";
    number: null;
} | {
    __kind__: "checkbox";
    checkbox: null;
} | {
    __kind__: "dropdown";
    dropdown: Array<string>;
}): Promise<{
    date: null;
} | {
    text: null;
} | {
    document: _ExternalBlob;
} | {
    number: null;
} | {
    checkbox: null;
} | {
    dropdown: Array<string>;
}> {
    return value.__kind__ === "date" ? {
        date: value.date
    } : value.__kind__ === "text" ? {
        text: value.text
    } : value.__kind__ === "document" ? {
        document: await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.document)
    } : value.__kind__ === "number" ? {
        number: value.number
    } : value.__kind__ === "checkbox" ? {
        checkbox: value.checkbox
    } : value.__kind__ === "dropdown" ? {
        dropdown: value.dropdown
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionType): {
    annual: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} {
    return value == SubscriptionType.annual ? {
        annual: null
    } : value == SubscriptionType.quarterly ? {
        quarterly: null
    } : value == SubscriptionType.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == SubmissionStatus.pending ? {
        pending: null
    } : value == SubmissionStatus.approved ? {
        approved: null
    } : value == SubmissionStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormCategory): {
    bpl: null;
} | {
    revenue: null;
} | {
    construction: null;
} | {
    rationCard: null;
} | {
    birthDeath: null;
} | {
    panchayat: null;
} | {
    income: null;
} | {
    marriage: null;
} | {
    nrega: null;
} {
    return value == FormCategory.bpl ? {
        bpl: null
    } : value == FormCategory.revenue ? {
        revenue: null
    } : value == FormCategory.construction ? {
        construction: null
    } : value == FormCategory.rationCard ? {
        rationCard: null
    } : value == FormCategory.birthDeath ? {
        birthDeath: null
    } : value == FormCategory.panchayat ? {
        panchayat: null
    } : value == FormCategory.income ? {
        income: null
    } : value == FormCategory.marriage ? {
        marriage: null
    } : value == FormCategory.nrega ? {
        nrega: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FormField>): Promise<Array<_FormField>> {
    return await Promise.all(value.map(async (x)=>await to_candid_FormField_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
